"""add free direct webrtc calls

Revision ID: 04dcb0ac44b7
Revises: 8715e0864ab4
Create Date: 2026-05-22 23:31:01.783788

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04dcb0ac44b7'
down_revision: Union[str, None] = '8715e0864ab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('started_by_id', sa.Uuid(), nullable=False),
    sa.Column('call_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_call_sessions_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['started_by_id'], ['users.id'], name=op.f('fk_call_sessions_started_by_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_sessions'))
    )
    op.create_index('ix_call_sessions_conversation_id', 'call_sessions', ['conversation_id'], unique=False)
    op.create_index('ix_call_sessions_started_by_id', 'call_sessions', ['started_by_id'], unique=False)
    op.create_table('call_participants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], name=op.f('fk_call_participants_call_session_id_call_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_call_participants_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_participants'))
    )
    op.create_index('ix_call_participants_call_session_id', 'call_participants', ['call_session_id'], unique=False)
    op.create_index('ix_call_participants_user_id', 'call_participants', ['user_id'], unique=False)
    op.create_table('call_signals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_session_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], name=op.f('fk_call_signals_call_session_id_call_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_call_signals_recipient_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_call_signals_sender_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_signals'))
    )
    op.create_index('ix_call_signals_call_session_id', 'call_signals', ['call_session_id'], unique=False)
    op.create_index('ix_call_signals_consumed_at', 'call_signals', ['consumed_at'], unique=False)
    op.create_index('ix_call_signals_recipient_id', 'call_signals', ['recipient_id'], unique=False)
    op.create_index('ix_call_signals_sender_id', 'call_signals', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_call_signals_sender_id', table_name='call_signals')
    op.drop_index('ix_call_signals_recipient_id', table_name='call_signals')
    op.drop_index('ix_call_signals_consumed_at', table_name='call_signals')
    op.drop_index('ix_call_signals_call_session_id', table_name='call_signals')
    op.drop_table('call_signals')
    op.drop_index('ix_call_participants_user_id', table_name='call_participants')
    op.drop_index('ix_call_participants_call_session_id', table_name='call_participants')
    op.drop_table('call_participants')
    op.drop_index('ix_call_sessions_started_by_id', table_name='call_sessions')
    op.drop_index('ix_call_sessions_conversation_id', table_name='call_sessions')
    op.drop_table('call_sessions')
    # ### end Alembic commands ###
