"""add_daily_stats_table

Revision ID: 2c6d34b20639
Revises: ac8d10b607c1
Create Date: 2026-05-14 00:22:38.110943

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c6d34b20639'
down_revision: Union[str, None] = 'ac8d10b607c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_stats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_hours', sa.Float(), nullable=False),
    sa.Column('is_late_login', sa.Boolean(), nullable=False),
    sa.Column('is_early_logout', sa.Boolean(), nullable=False),
    sa.Column('is_overtime', sa.Boolean(), nullable=False),
    sa.Column('is_absent', sa.Boolean(), nullable=False),
    sa.Column('leave_type', sa.Enum('sick', 'casual', 'annual', 'half_day', 'wfh', name='leave_type', native_enum=False), nullable=True),
    sa.Column('is_wfh', sa.Boolean(), nullable=False),
    sa.Column('primary_session_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_stats_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_stats')),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_daily_stats')
    )
    with op.batch_alter_table('account_invitations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_invitations', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    op.drop_table('daily_stats')
    # ### end Alembic commands ###
