"""initial_schema

Revision ID: 520e59672893
Revises: 
Create Date: 2026-04-23 22:05:53.373227

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '520e59672893'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'EMPLOYEE', name='user_role'), nullable=False),
    sa.Column('manager_id', sa.Uuid(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='user_status'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_manager_id', 'users', ['manager_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alert_type', sa.Enum('MISSING_CHECKOUT', 'OVERDUE_TASK', 'IDLE_AFTER_CHECKIN', 'SUSPICIOUS_LOGGING', 'APPROVAL_DELAY', 'BLOCKED_TASK', 'WORKLOAD_OVERLOAD', name='alert_type'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alert_severity'), nullable=False),
    sa.Column('recipient_user_id', sa.Uuid(), nullable=False),
    sa.Column('related_entity_type', sa.Enum('ATTENDANCE_SESSION', 'PROJECT', 'TASK', 'USER', 'APPROVAL', name='related_entity_type'), nullable=False),
    sa.Column('related_entity_id', sa.Uuid(), nullable=False),
    sa.Column('email_status', sa.Enum('QUEUED', 'SENT', 'FAILED', 'DISMISSED', name='alert_email_status'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'DISMISSED', name='alert_status'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_recipient_user_id_status_created_at', 'alerts', ['recipient_user_id', 'status', 'created_at'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.Enum('PROJECT', 'TIMESHEET', 'TASK', name='approval_entity_type'), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decision', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approval_status'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approvals_entity_type_entity_id', 'approvals', ['entity_type', 'entity_id'], unique=False)
    op.create_table('attendance_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('check_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('work_mode', sa.Enum('OFFICE', 'WFH', name='work_mode'), nullable=False),
    sa.Column('session_status', sa.Enum('ACTIVE', 'COMPLETED', 'INCOMPLETE', 'CORRECTED', name='attendance_session_status'), nullable=False),
    sa.Column('correction_requested', sa.Boolean(), nullable=False),
    sa.Column('correction_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attendance_sessions_user_id_check_in_at', 'attendance_sessions', ['user_id', 'check_in_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=128), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_entity_type_entity_id_created_at', 'audit_logs', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_table('performance_metrics_daily',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('total_session_minutes', sa.Integer(), nullable=False),
    sa.Column('productive_minutes', sa.Integer(), nullable=False),
    sa.Column('output_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('efficiency_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('utilization_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('consistency_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('composite_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'metric_date', name='uq_performance_metrics_user_date')
    )
    op.create_index('ix_performance_metrics_daily_user_id_metric_date', 'performance_metrics_daily', ['user_id', 'metric_date'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('manager_id', sa.Uuid(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='project_priority'), nullable=False),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approval_status'), nullable=False),
    sa.Column('project_status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'REJECTED', 'ARCHIVED', name='project_status'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_owner_id_approval_status', 'projects', ['owner_id', 'approval_status'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('manager_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('complexity_level', sa.Integer(), nullable=True),
    sa.Column('expected_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('actual_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='project_priority'), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'APPROVED', 'IN_PROGRESS', 'BLOCKED', 'COMPLETED', 'REVIEWED', 'REOPENED', name='task_status'), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_project_id_assigned_to_status', 'tasks', ['project_id', 'assigned_to', 'status'], unique=False)
    op.create_table('time_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.Enum('TIMER', 'MANUAL', name='time_log_source_type'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'INVALID', name='time_log_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_time_logs_task_id', 'time_logs', ['task_id'], unique=False)
    op.create_index('ix_time_logs_user_id_started_at', 'time_logs', ['user_id', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_time_logs_user_id_started_at', table_name='time_logs')
    op.drop_index('ix_time_logs_task_id', table_name='time_logs')
    op.drop_table('time_logs')
    op.drop_index('ix_tasks_project_id_assigned_to_status', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('teams')
    op.drop_index('ix_projects_owner_id_approval_status', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_performance_metrics_daily_user_id_metric_date', table_name='performance_metrics_daily')
    op.drop_table('performance_metrics_daily')
    op.drop_index('ix_audit_logs_entity_type_entity_id_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_attendance_sessions_user_id_check_in_at', table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    op.drop_index('ix_approvals_entity_type_entity_id', table_name='approvals')
    op.drop_table('approvals')
    op.drop_index('ix_alerts_recipient_user_id_status_created_at', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_users_manager_id', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
