"""add_ops_layer_missing_fields_and_tables

Revision ID: 523783759c79
Revises: bd327406aaad
Create Date: 2026-04-28 02:39:09.888310

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '523783759c79'
down_revision: Union[str, None] = 'bd327406aaad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # New Table: DailyStats
    op.create_table('daily_stats',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('total_hours', sa.Float(), nullable=False),
        sa.Column('is_late_login', sa.Boolean(), nullable=False),
        sa.Column('is_early_logout', sa.Boolean(), nullable=False),
        sa.Column('is_absent', sa.Boolean(), nullable=False),
        sa.Column('leave_type', sa.Enum('SICK', 'CASUAL', 'ANNUAL', 'HALF_DAY', 'WFH', name='leave_type'), nullable=True),
        sa.Column('is_wfh', sa.Boolean(), nullable=False),
        sa.Column('primary_session_id', sa.Uuid(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.UniqueConstraint('user_id', 'date', name='uq_user_daily_stats')
    )

    # New Table: ApprovalTimeline
    op.create_table('approval_timeline',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('entity_type', sa.String(), nullable=False),
        sa.Column('entity_id', sa.Uuid(), nullable=False),
        sa.Column('actor_id', sa.Uuid(), nullable=False),
        sa.Column('action', sa.String(), nullable=False),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['actor_id'], ['users.id'], )
    )

    with op.batch_alter_table('attendance_corrections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_check_in_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('original_check_out_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_late_login', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('is_early_logout', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('total_hours', sa.Float(), nullable=True))

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_half_day', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('half_day_period', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('current_approver_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('escalated_from_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('escalation_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_foreign_key('fk_leave_requests_escalated_from_id_users', 'users', ['escalated_from_id'], ['id'])
        batch_op.create_foreign_key('fk_leave_requests_current_approver_id_users', 'users', ['current_approver_id'], ['id'])

    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approval_timeline')
    op.drop_table('daily_stats')

    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_constraint('fk_leave_requests_current_approver_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_leave_requests_escalated_from_id_users', type_='foreignkey')
        batch_op.drop_column('escalation_count')
        batch_op.drop_column('escalated_at')
        batch_op.drop_column('escalated_from_id')
        batch_op.drop_column('current_approver_id')
        batch_op.drop_column('half_day_period')
        batch_op.drop_column('is_half_day')

    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.drop_column('total_hours')
        batch_op.drop_column('is_early_logout')
        batch_op.drop_column('is_late_login')

    with op.batch_alter_table('attendance_corrections', schema=None) as batch_op:
        batch_op.drop_column('original_check_out_at')
        batch_op.drop_column('original_check_in_at')

    # ### end Alembic commands ###
