"""production_initial_v1

Revision ID: 818032c93b4f
Revises: 
Create Date: 2026-05-01 05:44:30.444400

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '818032c93b4f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Shifts (No dependencies)
    op.create_table('shifts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('grace_period_minutes', sa.Integer(), nullable=False),
    sa.Column('working_days', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shifts'))
    )

    # 2. Users (Reference Shifts, but Departments FK added later)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'hr_operations', 'manager', 'team_lead', 'employee', 'intern', 'junior_employee', name='user_role', native_enum=False), nullable=False),
    sa.Column('manager_id', sa.Uuid(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('shift_id', sa.Uuid(), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', 'invited', name='user_status', native_enum=False), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_users_created_by_users')),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name=op.f('fk_users_manager_id_users')),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_users_shift_id_shifts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )

    # 3. Departments (Reference Users)
    op.create_table('departments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], name=op.f('fk_departments_admin_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('name', name=op.f('uq_departments_name'))
    )

    # 4. Late FK for Users -> Departments
    # SQLite cannot add constraints with ALTER TABLE, so use batch mode for
    # local development while keeping the same constraint for Postgres.
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.create_foreign_key(
                batch_op.f('fk_users_department_id_departments'),
                'departments',
                ['department_id'],
                ['id'],
            )
    else:
        op.create_foreign_key(op.f('fk_users_department_id_departments'), 'users', 'departments', ['department_id'], ['id'])

    op.create_table('holidays',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holidays')),
    sa.UniqueConstraint('holiday_date', name=op.f('uq_holidays_holiday_date'))
    )
    op.create_table('monthly_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_month', sa.Date(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('total_hours', sa.Integer(), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('late_logins', sa.Integer(), nullable=False),
    sa.Column('early_logouts', sa.Integer(), nullable=False),
    sa.Column('productivity_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monthly_reports'))
    )
    op.create_table('permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('key', name=op.f('uq_permissions_key'))
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('permission_key', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions')),
    sa.UniqueConstraint('role', 'permission_key', name='uq_role_permission')
    )
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_permissions_role'), ['role'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_email', ['email'], unique=False)
        batch_op.create_index('ix_users_manager_id', ['manager_id'], unique=False)

    op.create_table('account_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_account_invitations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_invitations'))
    )
    with op.batch_alter_table('account_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_invitations_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_account_invitations_user_id'), ['user_id'], unique=False)

    op.create_table('achievements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('badge_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_achievements_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievements'))
    )
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alert_type', sa.Enum('missing_checkout', 'overdue_task', 'idle_after_checkin', 'suspicious_logging', 'approval_delay', 'blocked_task', 'workload_overload', name='alert_type', native_enum=False), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='alert_severity', native_enum=False), nullable=False),
    sa.Column('recipient_user_id', sa.Uuid(), nullable=False),
    sa.Column('related_entity_type', sa.Enum('attendance_session', 'project', 'task', 'user', 'approval', name='related_entity_type', native_enum=False), nullable=False),
    sa.Column('related_entity_id', sa.Uuid(), nullable=False),
    sa.Column('email_status', sa.Enum('queued', 'sent', 'failed', 'dismissed', name='alert_email_status', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', 'dismissed', name='alert_status', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], name=op.f('fk_alerts_recipient_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('ix_alerts_recipient_user_id_status_created_at', ['recipient_user_id', 'status', 'created_at'], unique=False)

    op.create_table('announcements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_announcements_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcements'))
    )
    op.create_table('approvals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.Enum('project', 'timesheet', 'task', 'leave_request', 'attendance_correction', name='approval_entity_type', native_enum=False), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decision', sa.Enum('pending', 'approved', 'rejected', 'escalated', 'cancelled', 'needs_clarification', name='approval_status', native_enum=False), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_approvals_decided_by_users')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_approvals_requested_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals'))
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index('ix_approvals_entity_type_entity_id', ['entity_type', 'entity_id'], unique=False)

    op.create_table('attendance_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('check_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('work_mode', sa.Enum('office', 'wfh', name='work_mode', native_enum=False), nullable=False),
    sa.Column('session_status', sa.Enum('active', 'completed', 'incomplete', 'corrected', name='attendance_session_status', native_enum=False), nullable=False),
    sa.Column('is_late_login', sa.Boolean(), nullable=False),
    sa.Column('is_early_logout', sa.Boolean(), nullable=False),
    sa.Column('total_hours', sa.Float(), nullable=True),
    sa.Column('attendance_classification', sa.Enum('active', 'full_day', 'half_day', 'insufficient', 'leave', name='attendance_classification', native_enum=False), nullable=False),
    sa.Column('is_corrected', sa.Boolean(), nullable=False),
    sa.Column('correction_requested', sa.Boolean(), nullable=False),
    sa.Column('correction_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_attendance_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_sessions'))
    )
    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_attendance_sessions_user_id_check_in_at', ['user_id', 'check_in_at'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=128), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_entity_type_entity_id_created_at', ['entity_type', 'entity_id', 'created_at'], unique=False)

    op.create_table('eod_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('login_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('logout_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_hours', sa.Integer(), nullable=False),
    sa.Column('tasks_worked_on', sa.Integer(), nullable=False),
    sa.Column('completed_tasks', sa.Integer(), nullable=False),
    sa.Column('pending_tasks', sa.Integer(), nullable=False),
    sa.Column('blocked_tasks', sa.Integer(), nullable=False),
    sa.Column('duties_performed', sa.Integer(), nullable=False),
    sa.Column('productivity_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('manager_comments', sa.Text(), nullable=True),
    sa.Column('highlights_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_eod_reports_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eod_reports'))
    )
    op.create_table('goals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_metric', sa.String(length=50), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'achieved', 'failed', name='goal_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_goals_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goals'))
    )
    op.create_table('leave_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('leave_type', sa.Enum('sick', 'casual', 'annual', 'half_day', 'wfh', name='leave_type', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'escalated', 'cancelled', 'needs_clarification', name='leave_status', native_enum=False), nullable=False),
    sa.Column('is_half_day', sa.Boolean(), nullable=False),
    sa.Column('half_day_period', sa.Enum('first_half', 'second_half', name='half_day_period', native_enum=False), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('current_approver_id', sa.Uuid(), nullable=True),
    sa.Column('escalated_from_id', sa.Uuid(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalation_count', sa.Integer(), nullable=False),
    sa.Column('manager_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_approver_id'], ['users.id'], name=op.f('fk_leave_requests_current_approver_id_users')),
    sa.ForeignKeyConstraint(['escalated_from_id'], ['users.id'], name=op.f('fk_leave_requests_escalated_from_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_leave_requests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_requests'))
    )
    op.create_table('manager_daily_summaries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('manager_id', sa.Uuid(), nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('team_members_active', sa.Integer(), nullable=False),
    sa.Column('missing_checkouts', sa.Integer(), nullable=False),
    sa.Column('pending_approvals', sa.Integer(), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('overdue_tasks', sa.Integer(), nullable=False),
    sa.Column('blocked_tasks', sa.Integer(), nullable=False),
    sa.Column('eod_pending_approvals', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name=op.f('fk_manager_daily_summaries_manager_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manager_daily_summaries'))
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_reset_tokens_token_hash'))
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('performance_metrics_daily',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('total_session_minutes', sa.Integer(), nullable=False),
    sa.Column('productive_minutes', sa.Integer(), nullable=False),
    sa.Column('output_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('efficiency_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('utilization_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('consistency_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('composite_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_performance_metrics_daily_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_performance_metrics_daily')),
    sa.UniqueConstraint('user_id', 'metric_date', name='uq_performance_metrics_user_date')
    )
    with op.batch_alter_table('performance_metrics_daily', schema=None) as batch_op:
        batch_op.create_index('ix_performance_metrics_daily_user_id_metric_date', ['user_id', 'metric_date'], unique=False)

    op.create_table('personal_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('note_date', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_personal_notes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personal_notes'))
    )
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('manager_id', sa.Uuid(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='project_priority', native_enum=False), nullable=False),
    sa.Column('approval_status', sa.Enum('pending', 'approved', 'rejected', 'escalated', 'cancelled', 'needs_clarification', name='approval_status', native_enum=False), nullable=False),
    sa.Column('project_status', sa.Enum('draft', 'pending_approval', 'approved', 'active', 'on_hold', 'completed', 'rejected', 'archived', name='project_status', native_enum=False), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name=op.f('fk_projects_manager_id_users')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_projects_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('ix_projects_owner_id_approval_status', ['owner_id', 'approval_status'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('manager_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name=op.f('fk_teams_manager_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams'))
    )
    op.create_table('user_permission_overrides',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('permission_key', sa.String(length=100), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_permission_overrides_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_permission_overrides')),
    sa.UniqueConstraint('user_id', 'permission_key', name='uq_user_permission')
    )
    with op.batch_alter_table('user_permission_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_permission_overrides_user_id'), ['user_id'], unique=False)

    op.create_table('weekly_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_hours', sa.Integer(), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('pending_tasks', sa.Integer(), nullable=False),
    sa.Column('blocked_tasks', sa.Integer(), nullable=False),
    sa.Column('late_logins', sa.Integer(), nullable=False),
    sa.Column('early_logouts', sa.Integer(), nullable=False),
    sa.Column('eod_submission_rate', sa.Integer(), nullable=False),
    sa.Column('productivity_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_weekly_reports_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekly_reports'))
    )
    op.create_table('approval_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('approval_id', sa.Uuid(), nullable=False),
    sa.Column('approver_id', sa.Uuid(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('acted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated_to_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], name=op.f('fk_approval_steps_approval_id_approvals')),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], name=op.f('fk_approval_steps_approver_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_steps'))
    )
    op.create_table('attendance_corrections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('original_check_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('original_check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_check_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'needs_clarification', name='correction_status', native_enum=False), nullable=False),
    sa.Column('manager_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], name=op.f('fk_attendance_corrections_session_id_attendance_sessions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_attendance_corrections_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_corrections'))
    )
    op.create_table('eod_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('eod_report_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('manager_comments', sa.Text(), nullable=True),
    sa.Column('snapshot_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['eod_report_id'], ['eod_reports.id'], name=op.f('fk_eod_revisions_eod_report_id_eod_reports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eod_revisions'))
    )
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('complexity_level', sa.Integer(), nullable=True),
    sa.Column('expected_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('actual_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='project_priority', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('created', 'approved', 'in_progress', 'blocked', 'completed', 'reviewed', 'reopened', name='task_status', native_enum=False), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_tasks_assigned_to_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_tasks_created_by_users')),
    sa.ForeignKeyConstraint(['parent_id'], ['tasks.id'], name=op.f('fk_tasks_parent_id_tasks')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_tasks_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('ix_tasks_project_id_assigned_to_status', ['project_id', 'assigned_to', 'status'], unique=False)

    op.create_table('task_comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_comments_task_id_tasks')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_task_comments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_comments'))
    )
    op.create_table('time_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.Enum('timer', 'manual', name='time_log_source_type', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', 'invalid', name='time_log_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_time_logs_task_id_tasks')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_time_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_time_logs'))
    )
    with op.batch_alter_table('time_logs', schema=None) as batch_op:
        batch_op.create_index('ix_time_logs_task_id', ['task_id'], unique=False)
        batch_op.create_index('ix_time_logs_user_id_started_at', ['user_id', 'started_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_time_logs_user_id_started_at')
        batch_op.drop_index('ix_time_logs_task_id')

    op.drop_table('time_logs')
    op.drop_table('task_comments')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_tasks_project_id_assigned_to_status')

    op.drop_table('tasks')
    op.drop_table('eod_revisions')
    op.drop_table('attendance_corrections')
    op.drop_table('approval_steps')
    op.drop_table('weekly_reports')
    with op.batch_alter_table('user_permission_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_permission_overrides_user_id'))

    op.drop_table('user_permission_overrides')
    op.drop_table('teams')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('ix_projects_owner_id_approval_status')

    op.drop_table('projects')
    op.drop_table('personal_notes')
    with op.batch_alter_table('performance_metrics_daily', schema=None) as batch_op:
        batch_op.drop_index('ix_performance_metrics_daily_user_id_metric_date')

    op.drop_table('performance_metrics_daily')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))

    op.drop_table('password_reset_tokens')
    op.drop_table('manager_daily_summaries')
    op.drop_table('leave_requests')
    op.drop_table('goals')
    op.drop_table('eod_reports')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_entity_type_entity_id_created_at')

    op.drop_table('audit_logs')
    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_attendance_sessions_user_id_check_in_at')

    op.drop_table('attendance_sessions')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index('ix_approvals_entity_type_entity_id')

    op.drop_table('approvals')
    op.drop_table('announcements')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_alerts_recipient_user_id_status_created_at')

    op.drop_table('alerts')
    op.drop_table('achievements')
    with op.batch_alter_table('account_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_invitations_user_id'))
        batch_op.drop_index(batch_op.f('ix_account_invitations_token_hash'))

    op.drop_table('account_invitations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_manager_id')
        batch_op.drop_index('ix_users_email')

    op.drop_table('users')
    op.drop_table('shifts')
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_permissions_role'))

    op.drop_table('role_permissions')
    op.drop_table('permissions')
    op.drop_table('monthly_reports')
    op.drop_table('holidays')
    op.drop_table('departments')
    # ### end Alembic commands ###
