"""add message attachments

Revision ID: 8715e0864ab4
Revises: 6492fbe3a845
Create Date: 2026-05-22 23:19:42.542913

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8715e0864ab4'
down_revision: Union[str, None] = '6492fbe3a845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('uploader_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('original_file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('storage_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_message_attachments_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_attachments_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], name=op.f('fk_message_attachments_uploader_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_attachments'))
    )
    op.create_index('ix_message_attachments_conversation_id', 'message_attachments', ['conversation_id'], unique=False)
    op.create_index('ix_message_attachments_message_id', 'message_attachments', ['message_id'], unique=False)
    op.create_index('ix_message_attachments_uploader_id', 'message_attachments', ['uploader_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_attachments_uploader_id', table_name='message_attachments')
    op.drop_index('ix_message_attachments_message_id', table_name='message_attachments')
    op.drop_index('ix_message_attachments_conversation_id', table_name='message_attachments')
    op.drop_table('message_attachments')
    # ### end Alembic commands ###
