"""add_attendance_breaks

Revision ID: ac8d10b607c1
Revises: f85971bb5055
Create Date: 2026-05-14 00:17:22.205558

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac8d10b607c1'
down_revision: Union[str, None] = 'f85971bb5055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_breaks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('attendance_session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('break_type', sa.Enum('dinner', 'prayer', 'other', name='attendance_break_type', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attendance_session_id'], ['attendance_sessions.id'], name=op.f('fk_attendance_breaks_attendance_session_id_attendance_sessions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_attendance_breaks_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_breaks'))
    )
    op.drop_table('_alembic_tmp_account_invitations')
    with op.batch_alter_table('account_invitations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_break_minutes', sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column('dinner_break_minutes', sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column('prayer_break_minutes', sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column('other_break_minutes', sa.Integer(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.drop_column('other_break_minutes')
        batch_op.drop_column('prayer_break_minutes')
        batch_op.drop_column('dinner_break_minutes')
        batch_op.drop_column('total_break_minutes')

    with op.batch_alter_table('account_invitations', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    op.create_table('_alembic_tmp_account_invitations',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('user_id', sa.NUMERIC(), nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_account_invitations_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_account_invitations')
    )
    op.drop_table('attendance_breaks')
    # ### end Alembic commands ###
