"""add_account_invitations_and_invited_status

Revision ID: bd327406aaad
Revises: ffd924bea837
Create Date: 2026-04-24 04:10:22.045570

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd327406aaad'
down_revision: Union[str, None] = 'ffd924bea837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_account_invitations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_invitations'))
    )
    with op.batch_alter_table('account_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_invitations_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_account_invitations_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_invitations_user_id'))
        batch_op.drop_index(batch_op.f('ix_account_invitations_token_hash'))

    op.drop_table('account_invitations')
    # ### end Alembic commands ###
