"""Added shifts, leaves, eod, and growth features

Revision ID: d99e3d0d8bcc
Revises: 520e59672893
Create Date: 2026-04-24 02:13:46.585393

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd99e3d0d8bcc'
down_revision: Union[str, None] = '520e59672893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_departments_name'), ['name'])

    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_holidays_holiday_date'), ['holiday_date'])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_tasks_parent_id_tasks'), 'tasks', ['parent_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('shift_id', sa.Uuid(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])
        batch_op.create_foreign_key(batch_op.f('fk_users_department_id_departments'), 'departments', ['department_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_users_shift_id_shifts'), 'shifts', ['shift_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_shift_id_shifts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_users_department_id_departments'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')
        batch_op.drop_column('shift_id')
        batch_op.drop_column('department_id')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tasks_parent_id_tasks'), type_='foreignkey')

    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_holidays_holiday_date'), type_='unique')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_departments_name'), type_='unique')

    # ### end Alembic commands ###
