"""add communication center

Revision ID: f5cbb4ac7b32
Revises: 17535749ece3
Create Date: 2026-05-21 20:07:44.462367

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5cbb4ac7b32'
down_revision: Union[str, None] = '17535749ece3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('direct', 'group', 'channel', 'task_thread', 'project_thread', 'meeting_thread', 'support_thread', 'eod_thread', 'approval_thread', name='conversation_type', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('related_entity_type', sa.String(length=100), nullable=True),
    sa.Column('related_entity_id', sa.Uuid(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_conversations_created_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index('ix_conversations_created_at', 'conversations', ['created_at'], unique=False)
    op.create_index('ix_conversations_related_entity', 'conversations', ['related_entity_type', 'related_entity_id'], unique=False)
    op.create_table('conversation_participants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', 'viewer', name='conversation_participant_role', native_enum=False), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_participants_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversation_participants_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_participants'))
    )
    op.create_index('ix_conversation_participants_conv_user', 'conversation_participants', ['conversation_id', 'user_id'], unique=True)
    op.create_index('ix_conversation_participants_user_id', 'conversation_participants', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Enum('text', 'system', 'link', 'status_update', name='message_type', native_enum=False), nullable=False),
    sa.Column('parent_message_id', sa.Uuid(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_message_id'], ['messages.id'], name=op.f('fk_messages_parent_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_conversation_id', 'messages', ['conversation_id'], unique=False)
    op.create_index('ix_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_index('ix_messages_sender_id', 'messages', ['sender_id'], unique=False)
    op.create_table('message_mentions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('mentioned_user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['mentioned_user_id'], ['users.id'], name=op.f('fk_message_mentions_mentioned_user_id_users')),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_mentions_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_mentions'))
    )
    op.create_index('ix_message_mentions_user_id', 'message_mentions', ['mentioned_user_id'], unique=False)
    op.create_table('message_reactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('emoji', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_reactions_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_message_reactions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_reactions'))
    )
    op.create_index('ix_message_reactions_message_user', 'message_reactions', ['message_id', 'user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_reactions_message_user', table_name='message_reactions')
    op.drop_table('message_reactions')
    op.drop_index('ix_message_mentions_user_id', table_name='message_mentions')
    op.drop_table('message_mentions')
    op.drop_index('ix_messages_sender_id', table_name='messages')
    op.drop_index('ix_messages_created_at', table_name='messages')
    op.drop_index('ix_messages_conversation_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_conversation_participants_user_id', table_name='conversation_participants')
    op.drop_index('ix_conversation_participants_conv_user', table_name='conversation_participants')
    op.drop_table('conversation_participants')
    op.drop_index('ix_conversations_related_entity', table_name='conversations')
    op.drop_index('ix_conversations_created_at', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
