"""add_announcement_columns

Revision ID: f85971bb5055
Revises: 63e4ef16
Create Date: 2026-05-14 00:09:26.503596

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85971bb5055'
down_revision: Union[str, None] = '63e4ef16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    table_names = inspector.get_table_names()

    if 'approval_timeline' not in table_names:
        op.create_table('approval_timeline',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('entity_type', sa.Enum('project', 'timesheet', 'task', 'leave_request', 'attendance_correction', name='approval_entity_type', native_enum=False), nullable=False),
        sa.Column('entity_id', sa.Uuid(), nullable=False),
        sa.Column('actor_id', sa.Uuid(), nullable=False),
        sa.Column('action', sa.Enum('created', 'clarified', 'approved', 'rejected', 'escalated', 'cancelled', name='approval_action', native_enum=False), nullable=False),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_approval_timeline_actor_id_users')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_timeline'))
        )
        op.create_index('ix_approval_timeline_entity_type_entity_id', 'approval_timeline', ['entity_type', 'entity_id'], unique=False)

    if bind.dialect.name != 'sqlite' and 'account_invitations' in table_names:
        with op.batch_alter_table('account_invitations', schema=None) as batch_op:
            batch_op.alter_column('id',
                   existing_type=sa.NUMERIC(),
                   type_=sa.UUID(),
                   existing_nullable=False)
            batch_op.alter_column('user_id',
                   existing_type=sa.NUMERIC(),
                   type_=sa.UUID(),
                   existing_nullable=False)

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        announcement_columns = {column['name'] for column in inspector.get_columns('announcements')}
        if 'audience' not in announcement_columns:
            batch_op.add_column(sa.Column('audience', sa.String(length=50), nullable=False, server_default='all'))
        if 'start_date' not in announcement_columns:
            batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        if 'end_date' not in announcement_columns:
            batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        announcement_columns = {column['name'] for column in inspector.get_columns('announcements')}
        if 'end_date' in announcement_columns:
            batch_op.drop_column('end_date')
        if 'start_date' in announcement_columns:
            batch_op.drop_column('start_date')
        if 'audience' in announcement_columns:
            batch_op.drop_column('audience')

    if bind.dialect.name != 'sqlite' and 'account_invitations' in inspector.get_table_names():
        with op.batch_alter_table('account_invitations', schema=None) as batch_op:
            batch_op.alter_column('user_id',
                   existing_type=sa.UUID(),
                   type_=sa.NUMERIC(),
                   existing_nullable=False)
            batch_op.alter_column('id',
                   existing_type=sa.UUID(),
                   type_=sa.NUMERIC(),
                   existing_nullable=False)

    if 'approval_timeline' in inspector.get_table_names():
        op.drop_index('ix_approval_timeline_entity_type_entity_id', table_name='approval_timeline')
        op.drop_table('approval_timeline')

    # ### end Alembic commands ###
