"""add_announcement_columns

Revision ID: f85971bb5055
Revises: 63e4ef16
Create Date: 2026-05-14 00:09:26.503596

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85971bb5055'
down_revision: Union[str, None] = '63e4ef16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_timeline', schema=None) as batch_op:
        batch_op.drop_index('ix_approval_timeline_entity_type_entity_id')

    op.drop_table('approval_timeline')
    with op.batch_alter_table('account_invitations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audience', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('audience')

    with op.batch_alter_table('account_invitations', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    op.create_table('approval_timeline',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=21), nullable=False),
    sa.Column('entity_id', sa.CHAR(length=32), nullable=False),
    sa.Column('actor_id', sa.CHAR(length=32), nullable=False),
    sa.Column('action', sa.VARCHAR(length=9), nullable=False),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name='fk_approval_timeline_actor_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_approval_timeline')
    )
    with op.batch_alter_table('approval_timeline', schema=None) as batch_op:
        batch_op.create_index('ix_approval_timeline_entity_type_entity_id', ['entity_type', 'entity_id'], unique=False)

    # ### end Alembic commands ###
